services:
  db:
    image: postgres:16.4
    restart: always
    container_name: medtrain
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - "./create.ddl:/tmp/create.ddl"
      - "./master_data.sql:/tmp/master_data.sql"
      -  "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      -  "./.db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adobe
    network_mode: host